import * as _ from "../alphabet";
import { extendPunctuation } from "../extendRules";

export { keep as unknown } from "../handleUnrecognized";

export const table = extendPunctuation({
  2: _.hamza,
  a: _.alif,
  e: _.alif,
  b: _.ba,
  p: _.ba,
  t: _.taw,
  s: _.ta,
  th: _.ta,
  j: _.jim,
  dj: _.jim,
  g: _.jim,
  7: _.het,
  kh: _.kha,
  5: _.kha,
  "7'": _.kha,
  d: _.dal,
  z: _.dhal,
  dh: _.dhal,
  r: _.ra,
  z: _.zayn,
  s: _.sin,
  sh: _.shin,
  ch: _.shin,
  S: _.sad,
  9: _.sad,
  D: _.dad,
  "9'": _.dad,
  T: _.tha,
  6: _.tha,
  Z: _.za,
  "6'": _.za,
  3: _.ayn,
  gh: _.ghayn,
  "3'": _.ghayn,
  f: _.fa,
  v: _.fa,
  // 2: _.qaf,
  q: _.qaf,
  8: _.qaf,
  // 9: _.qaf,
  k: _.kaf,
  l: _.lam,
  m: _.mim,
  n: _.nun,
  h: _.ha,
  w: _.waw,
  o: _.waw,
  ou: _.waw,
  oo: _.waw,
  u: _.waw,
  y: _.ya,
  i: _.ya,
  ee: _.ya,
  "2a": _.maddah,
  // aa: _.maddah,
  at: _.marbutah,
  et: _.marbutah,
  A: _.maqsurah,
  "_": ""
});
